### ISSUE TITLE
IE class

### ISSUE THREAD

**Issue by yoyurec** [sureshdsk/browser-specific-css#5]
can you add general IE family class in addition to versioned class?
`ie10` -> `ie ie10`

**Comment by sainthardaway** [comment]
+1

**Comment by salieri328** [comment]
+1, it would be nice

**Comment by sureshdsk** [comment]
@yoyurec  @sainthardaway  @salieri328  added ie family class.. please do try it out..

**Comment by yoyurec** [comment]
:pray:

**Comment by sainthardaway** [comment]
@sureshdsk Many thanks
